<?php

use Illuminate\Database\Seeder;
use App\Country;


class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $data = [
            ['code' => 'US','name' => ['fr' => 'États-Unis', 'en' => 'United States']],
            ['code' => 'CA','name' => ['fr' => 'Canada', 'en' => 'Canada']],
            ['code' => 'AF','name' => ['fr' => 'Afghanistan', 'en' => 'Afghanistan']],
            ['code' => 'AL','name' => ['fr' => 'Albanie', 'en' => 'Albania']],
            ['code' => 'DZ','name' => ['fr' => 'Algérie', 'en' => 'Algeria']],
            ['code' => 'AS','name' => ['fr' => 'Samoa Américaines', 'en' => 'American Samoa']],
            ['code' => 'AD','name' => ['fr' => 'Andorre', 'en' => 'Andorra']],
            ['code' => 'AO','name' => ['fr' => 'Angola', 'en' => 'Angola']],
            ['code' => 'AI','name' => ['fr' => 'Anguilla', 'en' => 'Anguilla']],
            ['code' => 'AQ','name' => ['fr' => 'Antarctique', 'en' => 'Antarctica']],
            ['code' => 'AG','name' => ['fr' => 'Antigua-et-Barbuda', 'en' => 'Antigua and/or Barbuda']],
            ['code' => 'AR','name' => ['fr' => 'Argentine', 'en' => 'Argentina']],
            ['code' => 'AM','name' => ['fr' => 'Arménie', 'en' => 'Armenia']],
            ['code' => 'AW','name' => ['fr' => 'Aruba', 'en' => 'Aruba']],
            ['code' => 'AU','name' => ['fr' => 'Australie', 'en' => 'Australia']],
            ['code' => 'AT','name' => ['fr' => 'Autriche', 'en' => 'Austria']],
            ['code' => 'AZ','name' => ['fr' => 'Azerbaïdjan', 'en' => 'Azerbaijan']],
            ['code' => 'BS','name' => ['fr' => 'Bahamas', 'en' => 'Bahamas']],
            ['code' => 'BH','name' => ['fr' => 'Bahreïn', 'en' => 'Bahrain']],
            ['code' => 'BD','name' => ['fr' => 'Bangladesh', 'en' => 'Bangladesh']],
            ['code' => 'BB','name' => ['fr' => 'Barbade', 'en' => 'Barbados']],
            ['code' => 'BY','name' => ['fr' => 'Bélarus', 'en' => 'Belarus']],
            ['code' => 'BE','name' => ['fr' => 'Belgique', 'en' => 'Belgium']],
            ['code' => 'BZ','name' => ['fr' => 'Belize', 'en' => 'Belize']],
            ['code' => 'BJ','name' => ['fr' => 'Bénin', 'en' => 'Benin']],
            ['code' => 'BM','name' => ['fr' => 'Bermudes', 'en' => 'Bermuda']],
            ['code' => 'BT','name' => ['fr' => 'Bhoutan', 'en' => 'Bhutan']],
            ['code' => 'BO','name' => ['fr' => 'Bolivie', 'en' => 'Bolivia']],
            ['code' => 'BA','name' => ['fr' => 'Bosnie-Herzégovine', 'en' => 'Bosnia and Herzegovina']],
            ['code' => 'BW','name' => ['fr' => 'Botswana', 'en' => 'Botswana']],
            ['code' => 'BV','name' => ['fr' => 'Île Bouvet', 'en' => 'Bouvet Island']],
            ['code' => 'BR','name' => ['fr' => 'Brésil', 'en' => 'Brazil']],
            ['code' => 'IO','name' => ['fr' => 'Territoire britannique de l\'océan Indien', 'en' => 'British lndian Ocean Territory']],
            ['code' => 'BN','name' => ['fr' => 'Brunéi Darussalam', 'en' => 'Brunei Darussalam']],
            ['code' => 'BG','name' => ['fr' => 'Bulgarie', 'en' => 'Bulgaria']],
            ['code' => 'BF','name' => ['fr' => 'Burkina Faso', 'en' => 'Burkina Faso']],
            ['code' => 'BI','name' => ['fr' => 'Burundi', 'en' => 'Burundi']],
            ['code' => 'KH','name' => ['fr' => 'Cambodge', 'en' => 'Cambodia']],
            ['code' => 'CM','name' => ['fr' => 'Cameroun', 'en' => 'Cameroon']],
            ['code' => 'CV','name' => ['fr' => 'Cap-Vert', 'en' => 'Cape Verde']],
            ['code' => 'KY','name' => ['fr' => 'Caïmanes, Îles', 'en' => 'Cayman Islands']],
            ['code' => 'CF','name' => ['fr' => 'Centrafricaine, République', 'en' => 'Central African Republic']],
            ['code' => 'TD','name' => ['fr' => 'Tchad', 'en' => 'Chad']],
            ['code' => 'CL','name' => ['fr' => 'Chili', 'en' => 'Chile']],
            ['code' => 'CN','name' => ['fr' => 'Chine', 'en' => 'China']],
            ['code' => 'CX','name' => ['fr' => 'Île Christmas', 'en' => 'Christmas Island']],
            ['code' => 'CC','name' => ['fr' => 'Îles Cocos (Keeling)', 'en' => 'Cocos (Keeling) Islands']],
            ['code' => 'CO','name' => ['fr' => 'Colombie', 'en' => 'Colombia']],
            ['code' => 'KM','name' => ['fr' => 'Comores', 'en' => 'Comoros']],
            ['code' => 'CG','name' => ['fr' => 'Congo', 'en' => 'Congo']],
            ['code' => 'CK','name' => ['fr' => 'Îles Cook', 'en' => 'Cook Islands']],
            ['code' => 'CR','name' => ['fr' => 'Costa Rica', 'en' => 'Costa Rica']],
            ['code' => 'HR','name' => ['fr' => 'Croatie', 'en' => 'Croatia (Hrvatska)']],
            ['code' => 'CU','name' => ['fr' => 'Cuba', 'en' => 'Cuba']],
            ['code' => 'CY','name' => ['fr' => 'Chypre', 'en' => 'Cyprus']],
            ['code' => 'CZ','name' => ['fr' => 'République Tchèque', 'en' => 'Czech Republic']],
            ['code' => 'CD','name' => ['fr' => 'République Démocratique du Congo', 'en' => 'Democratic Republic of Congo']],
            ['code' => 'DK','name' => ['fr' => 'Danemark', 'en' => 'Denmark']],
            ['code' => 'DJ','name' => ['fr' => 'Djibouti', 'en' => 'Djibouti']],
            ['code' => 'DM','name' => ['fr' => 'Dominique', 'en' => 'Dominica']],
            ['code' => 'DO','name' => ['fr' => 'République Dominicaine', 'en' => 'Dominican Republic']],
            ['code' => 'TP','name' => ['fr' => 'Timor-Leste (Timor Oriental)', 'en' => 'East Timor']],
            ['code' => 'EC','name' => ['fr' => 'Équateur', 'en' => 'Ecudaor']],
            ['code' => 'EG','name' => ['fr' => 'Égypte', 'en' => 'Egypt']],
            ['code' => 'SV','name' => ['fr' => 'El Salvador', 'en' => 'El Salvador']],
            ['code' => 'GQ','name' => ['fr' => 'Guinée Équatoriale', 'en' => 'Equatorial Guinea']],
            ['code' => 'ER','name' => ['fr' => 'Érythrée', 'en' => 'Eritrea']],
            ['code' => 'EE','name' => ['fr' => 'Estonie', 'en' => 'Estonia']],
            ['code' => 'ET','name' => ['fr' => 'Éthiopie', 'en' => 'Ethiopia']],
            ['code' => 'FK','name' => ['fr' => '', 'en' => 'Falkland Islands (Malvinas)']],
            ['code' => 'FO','name' => ['fr' => 'Îles Féroé', 'en' => 'Faroe Islands']],
            ['code' => 'FJ','name' => ['fr' => 'Fidji', 'en' => 'Fiji']],
            ['code' => 'FI','name' => ['fr' => 'Finlande', 'en' => 'Finland']],
            ['code' => 'FR','name' => ['fr' => 'France', 'en' => 'France']],
            ['code' => 'GF','name' => ['fr' => 'Guyane Française', 'en' => 'French Guiana']],
            ['code' => 'PF','name' => ['fr' => 'Polynésie Française', 'en' => 'French Polynesia']],
            ['code' => 'TF','name' => ['fr' => 'Terres Australes Françaises', 'en' => 'French Southern Territories']],
            ['code' => 'GA','name' => ['fr' => 'Gabon', 'en' => 'Gabon']],
            ['code' => 'GM','name' => ['fr' => 'Gambie', 'en' => 'Gambia']],
            ['code' => 'GE','name' => ['fr' => 'Géorgie', 'en' => 'Georgia']],
            ['code' => 'DE','name' => ['fr' => 'Allemagne', 'en' => 'Germany']],
            ['code' => 'GH','name' => ['fr' => 'Ghana', 'en' => 'Ghana']],
            ['code' => 'GI','name' => ['fr' => 'Gibraltar', 'en' => 'Gibraltar']],
            ['code' => 'GR','name' => ['fr' => 'Grèce', 'en' => 'Greece']],
            ['code' => 'GL','name' => ['fr' => 'Groenland', 'en' => 'Greenland']],
            ['code' => 'GD','name' => ['fr' => 'Grenade', 'en' => 'Grenada']],
            ['code' => 'GP','name' => ['fr' => 'Guadeloupe', 'en' => 'Guadeloupe']],
            ['code' => 'GU','name' => ['fr' => 'Guam', 'en' => 'Guam']],
            ['code' => 'GT','name' => ['fr' => 'Guatemala', 'en' => 'Guatemala']],
            ['code' => 'GN','name' => ['fr' => 'Guinéee', 'en' => 'Guinea']],
            ['code' => 'GW','name' => ['fr' => 'Guinée-Bissau', 'en' => 'Guinea-Bissau']],
            ['code' => 'GY','name' => ['fr' => 'Guyana', 'en' => 'Guyana']],
            ['code' => 'HT','name' => ['fr' => 'Haïti', 'en' => 'Haiti']],
            ['code' => 'HM','name' => ['fr' => 'Îles Heard-et-MacDonald', 'en' => 'Heard and Mc Donald Islands']],
            ['code' => 'HN','name' => ['fr' => 'Honduras', 'en' => 'Honduras']],
            ['code' => 'HK','name' => ['fr' => 'Hong-Kong', 'en' => 'Hong Kong']],
            ['code' => 'HU','name' => ['fr' => 'Hongrie', 'en' => 'Hungary']],
            ['code' => 'IS','name' => ['fr' => 'Islande', 'en' => 'Iceland']],
            ['code' => 'IN','name' => ['fr' => 'Inde', 'en' => 'India']],
            ['code' => 'ID','name' => ['fr' => 'Indonésie', 'en' => 'Indonesia']],
            ['code' => 'IR','name' => ['fr' => 'République Islamique d
            \'Iran', 'en' => 'Iran (Islamic Republic of)']],
            ['code' => 'IQ','name' => ['fr' => 'Iraq', 'en' => 'Iraq']],
            ['code' => 'IE','name' => ['fr' => 'Irlande', 'en' => 'Ireland']],
            ['code' => 'IL','name' => ['fr' => 'Israël', 'en' => 'Israel']],
            ['code' => 'IT','name' => ['fr' => 'Italie', 'en' => 'Italy']],
            ['code' => 'CI','name' => ['fr' => 'Côte D\'ivoire', 'en' => 'Ivory Coast']],
            ['code' => 'JM','name' => ['fr' => 'Jamaïque', 'en' => 'Jamaica']],
            ['code' => 'JP','name' => ['fr' => 'Japon', 'en' => 'Japan']],
            ['code' => 'JO','name' => ['fr' => 'Jordanie', 'en' => 'Jordan']],
            ['code' => 'KZ','name' => ['fr' => 'Kazakstan', 'en' => 'Kazakhstan']],
            ['code' => 'KE','name' => ['fr' => 'Kenya', 'en' => 'Kenya']],
            ['code' => 'KI','name' => ['fr' => 'Kiribati', 'en' => 'Kiribati']],
            ['code' => 'KP','name' => ['fr' => 'Corée, République Populaire Démocratique de', 'en' => 'Korea, Democratic People\'s Republic of']],
            ['code' => 'KR','name' => ['fr' => 'Corée, République de', 'en' => 'Korea, Republic of']],
            ['code' => 'KW','name' => ['fr' => 'Koweït', 'en' => 'Kuwait']],
            ['code' => 'KG','name' => ['fr' => 'Kirghizistan', 'en' => 'Kyrgyzstan']],
            ['code' => 'LA','name' => ['fr' => 'Lao, République Démocratique Populaire', 'en' => 'Lao People\'s Democratic Republic']],
            ['code' => 'LV','name' => ['fr' => 'Lettonie', 'en' => 'Latvia']],
            ['code' => 'LB','name' => ['fr' => 'Liban', 'en' => 'Lebanon']],
            ['code' => 'LS','name' => ['fr' => 'Lesotho', 'en' => 'Lesotho']],
            ['code' => 'LR','name' => ['fr' => 'Libéria', 'en' => 'Liberia']],
            ['code' => 'LY','name' => ['fr' => 'Libye', 'en' => 'Libyan Arab Jamahiriya']],
            ['code' => 'LI','name' => ['fr' => 'Liechtenstein', 'en' => 'Liechtenstein']],
            ['code' => 'LT','name' => ['fr' => 'Lituanie', 'en' => 'Lithuania']],
            ['code' => 'LU','name' => ['fr' => 'Luxembourg', 'en' => 'Luxembourg']],
            ['code' => 'MO','name' => ['fr' => 'Macao', 'en' => 'Macau']],
            ['code' => 'MK','name' => ['fr' => 'Macédoine', 'en' => 'Macedonia']],
            ['code' => 'MG','name' => ['fr' => 'Madagascar', 'en' => 'Madagascar']],
            ['code' => 'MW','name' => ['fr' => 'Malawi', 'en' => 'Malawi']],
            ['code' => 'MY','name' => ['fr' => 'Malaisie', 'en' => 'Malaysia']],
            ['code' => 'MV','name' => ['fr' => 'Maldives', 'en' => 'Maldives']],
            ['code' => 'ML','name' => ['fr' => 'Mali', 'en' => 'Mali']],
            ['code' => 'MT','name' => ['fr' => 'Malte', 'en' => 'Malta']],
            ['code' => 'MH','name' => ['fr' => 'Îles Marshall', 'en' => 'Marshall Islands']],
            ['code' => 'MQ','name' => ['fr' => 'Martinique', 'en' => 'Martinique']],
            ['code' => 'MR','name' => ['fr' => 'Mauritanie', 'en' => 'Mauritania']],
            ['code' => 'MU','name' => ['fr' => 'Île Maurice', 'en' => 'Mauritius']],
            ['code' => 'TY','name' => ['fr' => 'Mayotte', 'en' => 'Mayotte']],
            ['code' => 'MX','name' => ['fr' => 'Mexique', 'en' => 'Mexico']],
            ['code' => 'FM','name' => ['fr' => 'États Fédérés de Micronésie', 'en' => 'Micronesia, Federated States of']],
            ['code' => 'MD','name' => ['fr' => 'Moldova, République de', 'en' => 'Moldova, Republic of']],
            ['code' => 'MC','name' => ['fr' => 'Monaco', 'en' => 'Monaco']],
            ['code' => 'MN','name' => ['fr' => 'Mongolie', 'en' => 'Mongolia']],
            ['code' => 'MS','name' => ['fr' => 'Montserrat', 'en' => 'Montserrat']],
            ['code' => 'MA','name' => ['fr' => 'Maroc', 'en' => 'Morocco']],
            ['code' => 'MZ','name' => ['fr' => 'Mozambique', 'en' => 'Mozambique']],
            ['code' => 'MM','name' => ['fr' => 'Myanmar', 'en' => 'Myanmar']],
            ['code' => 'NA','name' => ['fr' => 'Namibie', 'en' => 'Namibia']],
            ['code' => 'NR','name' => ['fr' => 'Nauru', 'en' => 'Nauru']],
            ['code' => 'NP','name' => ['fr' => 'Népal', 'en' => 'Nepal']],
            ['code' => 'NL','name' => ['fr' => 'Pays-Bas', 'en' => 'Netherlands']],
            ['code' => 'AN','name' => ['fr' => 'Antilles Néerlandaises', 'en' => 'Netherlands Antilles']],
            ['code' => 'NC','name' => ['fr' => 'Nouvelle-Calédonie', 'en' => 'New Caledonia']],
            ['code' => 'NZ','name' => ['fr' => 'Nouvelle-Zélande', 'en' => 'New Zealand']],
            ['code' => 'NI','name' => ['fr' => 'Nicaragua', 'en' => 'Nicaragua']],
            ['code' => 'NE','name' => ['fr' => 'Niger', 'en' => 'Niger']],
            ['code' => 'NG','name' => ['fr' => 'Nigéria', 'en' => 'Nigeria']],
            ['code' => 'NU','name' => ['fr' => 'Nioué', 'en' => 'Niue']],
            ['code' => 'NF','name' => ['fr' => 'Île Norfolk', 'en' => 'Norfork Island']],
            ['code' => 'MP','name' => ['fr' => 'Îles Mariannes du Nord', 'en' => 'Northern Mariana Islands']],
            ['code' => 'NO','name' => ['fr' => 'Norvège', 'en' => 'Norway']],
            ['code' => 'OM','name' => ['fr' => 'Oman', 'en' => 'Oman']],
            ['code' => 'PK','name' => ['fr' => 'Pakistan', 'en' => 'Pakistan']],
            ['code' => 'PW','name' => ['fr' => 'Palaos', 'en' => 'Palau']],
            ['code' => 'PA','name' => ['fr' => 'Panama', 'en' => 'Panama']],
            ['code' => 'PG','name' => ['fr' => 'Papouasie-Nouvelle-Guinée', 'en' => 'Papua New Guinea']],
            ['code' => 'PY','name' => ['fr' => 'Paraguay', 'en' => 'Paraguay']],
            ['code' => 'PE','name' => ['fr' => 'Pérou', 'en' => 'Peru']],
            ['code' => 'PH','name' => ['fr' => 'Philippines', 'en' => 'Philippines']],
            ['code' => 'PN','name' => ['fr' => 'Pitcairn', 'en' => 'Pitcairn']],
            ['code' => 'PL','name' => ['fr' => 'Pologne', 'en' => 'Poland']],
            ['code' => 'PT','name' => ['fr' => 'Portugal', 'en' => 'Portugal']],
            ['code' => 'PR','name' => ['fr' => 'Porto Rico', 'en' => 'Puerto Rico']],
            ['code' => 'QA','name' => ['fr' => 'Qatar', 'en' => 'Qatar']],
            ['code' => 'SS','name' => ['fr' => 'Soudan du Sud', 'en' => 'Republic of South Sudan']],
            ['code' => 'RE','name' => ['fr' => 'Ile de la Réunion', 'en' => 'Reunion Island']],
            ['code' => 'RO','name' => ['fr' => 'Roumanie', 'en' => 'Romania']],
            ['code' => 'RU','name' => ['fr' => 'Russie, Fédération de', 'en' => 'Russian Federation']],
            ['code' => 'RW','name' => ['fr' => 'Rwanda', 'en' => 'Rwanda']],
            ['code' => 'KN','name' => ['fr' => 'Saint-Kitts-et-Nevis', 'en' => 'Saint Kitts and Nevis']],
            ['code' => 'LC','name' => ['fr' => 'Sainte-Lucie', 'en' => 'Saint Lucia']],
            ['code' => 'VC','name' => ['fr' => 'Saint-Vincent-et-les Grenadines', 'en' => 'Saint Vincent and the Grenadines']],
            ['code' => 'WS','name' => ['fr' => 'Samoa', 'en' => 'Samoa']],
            ['code' => 'SM','name' => ['fr' => 'Saint-Marin', 'en' => 'San Marino']],
            ['code' => 'ST','name' => ['fr' => 'Sao Tomé-et-Principe', 'en' => 'Sao Tome and Principe']],
            ['code' => 'SA','name' => ['fr' => 'Arabie Saoudite', 'en' => 'Saudi Arabia']],
            ['code' => 'SN','name' => ['fr' => 'Sénégal', 'en' => 'Senegal']],
            ['code' => 'RS','name' => ['fr' => 'Serbie', 'en' => 'Serbia']],
            ['code' => 'SC','name' => ['fr' => 'Seychelles', 'en' => 'Seychelles']],
            ['code' => 'SL','name' => ['fr' => 'Sierra Leone', 'en' => 'Sierra Leone']],
            ['code' => 'SG','name' => ['fr' => 'Singapour', 'en' => 'Singapore']],
            ['code' => 'SK','name' => ['fr' => 'Slovaquie', 'en' => 'Slovakia']],
            ['code' => 'SI','name' => ['fr' => 'Slovénie', 'en' => 'Slovenia']],
            ['code' => 'SB','name' => ['fr' => 'Salomon, Îles', 'en' => 'Solomon Islands']],
            ['code' => 'SO','name' => ['fr' => 'Somalie', 'en' => 'Somalia']],
            ['code' => 'ZA','name' => ['fr' => 'Afrique du Sud', 'en' => 'South Africa']],
            ['code' => 'GS','name' => ['fr' => 'Géorgie du Sud-et-les îles Sandwich du Sud', 'en' => 'South Georgia South Sandwich Islands']],
            ['code' => 'ES','name' => ['fr' => 'Espagne', 'en' => 'Spain']],
            ['code' => 'LK','name' => ['fr' => 'Sri Lanka', 'en' => 'Sri Lanka']],
            ['code' => 'SH','name' => ['fr' => 'Sainte-Hélène (île)', 'en' => 'St. Helena']],
            ['code' => 'PM','name' => ['fr' => 'Saint-Pierre-et-Miquelon', 'en' => 'St. Pierre and Miquelon']],
            ['code' => 'SD','name' => ['fr' => 'Soudan', 'en' => 'Sudan']],
            ['code' => 'SR','name' => ['fr' => 'Suriname', 'en' => 'Suriname']],
            ['code' => 'SJ','name' => ['fr' => 'Svalbard et Jan Mayen', 'en' => 'Svalbarn and Jan Mayen Islands']],
            ['code' => 'SZ','name' => ['fr' => 'Swaziland', 'en' => 'Swaziland']],
            ['code' => 'SE','name' => ['fr' => 'Suède', 'en' => 'Sweden']],
            ['code' => 'CH','name' => ['fr' => 'Suisse', 'en' => 'Switzerland']],
            ['code' => 'SY','name' => ['fr' => 'Syrienne, République Arabe', 'en' => 'Syrian Arab Republic']],
            ['code' => 'TW','name' => ['fr' => 'Taïwan', 'en' => 'Taiwan']],
            ['code' => 'TJ','name' => ['fr' => 'Tadjikistan', 'en' => 'Tajikistan']],
            ['code' => 'TZ','name' => ['fr' => 'Tanzanie, République-Unie de', 'en' => 'Tanzania, United Republic of']],
            ['code' => 'TH','name' => ['fr' => 'Thaïlande', 'en' => 'Thailand']],
            ['code' => 'TIB','name' => ['fr' => 'Tibet', 'en' => 'Tibet']],
            ['code' => 'TG','name' => ['fr' => 'Togo', 'en' => 'Togo']],
            ['code' => 'TK','name' => ['fr' => 'Tokelau', 'en' => 'Tokelau']],
            ['code' => 'TO','name' => ['fr' => 'Tonga', 'en' => 'Tonga']],
            ['code' => 'TT','name' => ['fr' => 'Trinité-et-Tobago', 'en' => 'Trinidad and Tobago']],
            ['code' => 'TN','name' => ['fr' => 'Tunisie', 'en' => 'Tunisia']],
            ['code' => 'TR','name' => ['fr' => 'Turquie', 'en' => 'Turkey']],
            ['code' => 'TM','name' => ['fr' => 'Turkménistan', 'en' => 'Turkmenistan']],
            ['code' => 'TC','name' => ['fr' => 'Turks et Caïques, Îles', 'en' => 'Turks and Caicos Islands']],
            ['code' => 'TV','name' => ['fr' => 'Tuvalu', 'en' => 'Tuvalu']],
            ['code' => 'UG','name' => ['fr' => 'Ouganda', 'en' => 'Uganda']],
            ['code' => 'UA','name' => ['fr' => 'Ukraine', 'en' => 'Ukraine']],
            ['code' => 'AE','name' => ['fr' => 'Émirats Arabes Unis', 'en' => 'United Arab Emirates']],
            ['code' => 'GB','name' => ['fr' => 'Royaume-Uni', 'en' => 'United Kingdom']],
            ['code' => 'UY','name' => ['fr' => 'Uruguay', 'en' => 'Uruguay']],
            ['code' => 'UZ','name' => ['fr' => 'Ouzbékistan', 'en' => 'Uzbekistan']],
            ['code' => 'VU','name' => ['fr' => 'Vanuatu', 'en' => 'Vanuatu']],
            ['code' => 'VA','name' => ['fr' => 'Saint-Siège (État de la Cité du Vatican)', 'en' => 'Vatican City State']],
            ['code' => 'VE','name' => ['fr' => 'Venezuela', 'en' => 'Venezuela']],
            ['code' => 'VN','name' => ['fr' => 'Viêt Nam', 'en' => 'Vietnam']],
            ['code' => 'VG','name' => ['fr' => 'Îles Vierges britanniques', 'en' => 'Virgin Islands (British)']],
            ['code' => 'VI','name' => ['fr' => 'Îles Vierges des États-Unis', 'en' => 'Virgin Islands (U.S.)']],
            ['code' => 'WF','name' => ['fr' => 'Wallis et Futuna', 'en' => 'Wallis and Futuna Islands']],
            ['code' => 'EH','name' => ['fr' => 'Sahara Occidental', 'en' => 'Western Sahara']],
            ['code' => 'YE','name' => ['fr' => 'Yémen', 'en' => 'Yemen']],
            ['code' => 'ZM','name' => ['fr' => 'Zambie', 'en' => 'Zambia']],
            ['code' => 'ZW','name' => ['fr' => 'Zimbabwe', 'en' => 'Zimbabwe']],
        ];
        foreach ($data as $item) {
            $model = new Country();
            $model->code = $item['code'];
            foreach ($item['name'] as $locale => $subitem) {
                app()->setLocale($locale);
                $model->name = $subitem;
            }
            $model->save();

        }
    }
}
